### ISSUE TITLE
数据收集区

### ISSUE THREAD

**Issue by awall2002** [awall2002/confesstalker#1]
[confess.zip](https://github.com/awall2002/confesstalker/files/2148686/confess.zip)

已知数据

**Comment by DUWENINK** [comment]
S1oKvPoK6kow65oK45NKCiowcs :353342988
S1oKvPoK6kow6zNK-qoiCz7eCA :3108817960
S1oKvPoK6kow65oeEq7iC57K4i :3060647504
S1oKvPoK6kow65oKn57KoP7i-l :2505449050
S1oKvPoK6kow65oK4sNe4kNKoA :2467569583
S1oKvPoK6kow6zNeEsowclowoq :1738004309

**Comment by DUWENINK** [comment]
S1oKvPoK6kow65oKCz7eEFoioq
S1oKvPoK6kow6zNKSA7eSz7Koz 这两个QQ是同一个人的

**Comment by awall2002** [comment]
您好，请问这两个的ＱＱ号是。。。

**Comment by DUWENINK** [comment]
我建议你做一个小程序让用户可以提交到你的收据库里边,然后在给个备份下载链接

**Comment by sanxiaozhizi** [comment]
\*S1\*oKvPoK6kow6zNKnPow4FoKcl：1580359334

**Comment by gxh27954** [comment]
可以建个群，对这事有兴趣的人一起探讨

**Comment by easygoto** [comment]
*S1*oKvPoK6kow65oeCi7K-lNKo5: 595603389
*S1*oKvPoK6kow65ownl7i-zNeEk: 1392605506

前面的*S1*oKvPoK6kow6基本都是一样的

**Comment by chunandaxueshi** [comment]
*S1*oKvPoK6kow65ow4ANK6i7Kvl: 3076403766

**Comment by bayllech** [comment]
*S1*oKvPoK6kow65oensoKv5oKSk：824097513

**Comment by lqwqc987** [comment]
各位大佬群加不了了
